/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConnectionType The type of a connection
type ConnectionType string

// List of ConnectionType
const (
	AMQP_091 ConnectionType = "amqp-091"
	AMQP_10 ConnectionType = "amqp-10"
	MQTT ConnectionType = "mqtt"
	KAFKA ConnectionType = "kafka"
)
