/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package things
// SolutionPlanObject The booked plan as object representation.
type SolutionPlanObject struct {
	Type PlanType `json:"type,omitempty"`
	UsageLimits UsageLimits `json:"usageLimits,omitempty"`
}
