/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MappingContext MappingContext to apply in this connection containing JavaScript scripts mapping from external messages to internal Ditto Protocol messages. Usage of MappingContext is deprecated, use PayloadMappingDefinitions instead.
type MappingContext struct {
	// The mapping script for incoming messages
	IncomingScript string `json:"incomingScript"`
	// The mapping script for outgoing messages
	OutgoingScript string `json:"outgoingScript"`
	// Whether or not ByteBufferJS library should be included
	LoadBytebufferJS bool `json:"loadBytebufferJS"`
	// Whether or not LongJS library should be included
	LoadLongJS bool `json:"loadLongJS"`
}
