/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConnectionLogs Log entries of a connection.
type ConnectionLogs struct {
	// ID of the connection for which the log entries were logged.
	ConnectionId string `json:"connectionId"`
	// Log entries for the connection.
	ConnectionLogs []LogEntry `json:"connectionLogs"`
	// Since when logging is enabled. Might be missing / null if logging is not enabled.
	EnabledSince string `json:"enabledSince,omitempty"`
	// Until when logging is enabled. Might be missing / null if logging is not enabled.
	EnabledUntil string `json:"enabledUntil,omitempty"`
}
