/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package things
// PayloadMappingDefinition A mapping definition consisting of the used mappingEngine and the options required by this engine.
type PayloadMappingDefinition struct {
	// The mapping engine used to process incoming and outgoing messages. Available mapping engines are `JavaScript`, `Normalized`, `ConnectionStatus`, `Ditto`.
	MappingEngine string `json:"mappingEngine"`
	// Configuration options specific to the used mapping engine:  #### JavaScript   * `incomingScript` (`string`, required): The mapping script for incoming messages   * `outgoingScript` (`string`, required): The mapping script for outgoing messages   * `loadBytebufferJS` (`boolean`, optional): Whether or not ByteBufferJS library should be included     (default: `false`)   * `loadLongJS` (`boolean`, optional): Whether or not LongJS library should be included (default: `false`)  #### Normalized   * `fields` (`string`, optional): Comma separated list of fields included in the normalized message     (default: all fields included)  #### ConnectionStatus   * `thingId` (`string`, required): The ID of the thing   * `featureId` (`string`, optional): The ID of the modified feature (default: `ConnectionStatus`)  #### Ditto   * no options required
	Options map[string]interface{} `json:"options"`
}
