/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package things
// LogEntry Represents a log entry for a connection.
type LogEntry struct {
	// Timestamp of the log entry.
	Timestamp string `json:"timestamp"`
	// Correlation ID that is associated with the log entry.
	CorrelationId string `json:"correlationId"`
	// The log message.
	Message string `json:"message"`
	Category LogCategory `json:"category"`
	Type LogType `json:"type"`
	Level LogLevel `json:"level"`
	// Connection address on which the log occured.
	Address string `json:"address,omitempty"`
	// The thing for which the log entry was created.
	ThingId string `json:"thingId,omitempty"`
}
