/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ResourceStatus The status of a single resource (e.g. a client or a source/target resource)
type ResourceStatus struct {
	// The type of the resource
	Type string `json:"type"`
	// A client identifier where the resource is held (e.g. a cluster instance ID)
	Client string `json:"client"`
	// The address information of the resource (optional)
	Address string `json:"address,omitempty"`
	Status ConnectivityStatus `json:"status"`
	// Details to the status of the resource
	StatusDetails string `json:"statusDetails,omitempty"`
	// Date since when the resource is in the present state
	InStateSince string `json:"inStateSince,omitempty"`
}
