/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package things
// LogCategory A category to which the log entry can be referred to.
type LogCategory string

// List of LogCategory
const (
	SOURCE LogCategory = "source"
	TARGET LogCategory = "target"
	RESPONSE LogCategory = "response"
	CONNECTION LogCategory = "connection"
)
