/*
 * Bosch IoT Things HTTP API
 *
 * Bosch IoT Things enables applications to manage digital twins of IoT device assets in a simple, convenient, robust, and secure way.  These descriptions focus on the JSON-based, REST-like **HTTP API 2** of the Bosch IoT Things service.  Find details in our [documentation](https://docs.bosch-iot-suite.com/things/).
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Usage Object holding the data volume, transaction count and the time when this data was calculated.
type Usage struct {
	DataVolume DataVolume `json:"dataVolume,omitempty"`
	TransactionCount TransactionCount `json:"transactionCount,omitempty"`
	// the time when this usage was calculated. Format of the string complies with ISO-8601.
	TimeOfCalculation string `json:"timeOfCalculation,omitempty"`
}
